# Test 2024-05-04 at 19:18:59
# wire3c in play when going to a new level, wires drawn from longest to shortest.

name: Test

run-name: #!/usr/bin/perl -I/home/phil/perl/cpan/SvgSimple/lib/ -I/home/phil/perl/cpan/SiliconChip/lib/ -I/home/phil/perl/cpan/SiliconChipLayout/lib/ -I/home/phil/perl/cpan/SiliconChipWiring/lib/ -I/home/phil/perl/cpan/Math-Intersection-Circle-Line/lib
#-------------------------------------------------------------------------------
# Implement a B-Tree as a silicon chip.
# Philip R Brenan at appaapps dot com, Appa Apps Ltd Inc., 2023
#-------------------------------------------------------------------------------
# Database on a chip: high speed low power database look ups save data center operators money on their electricity bills.
use v5.34;
package Silicon::Chip::Btree;
our $VERSION = 20240331;                                                        # Version
use warnings FATAL => qw(all

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SiliconChip
        path: sc

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SiliconChipLayout
        path: layout

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SiliconChipWiring
        path: wiring

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/MathIntersectionCircleLine
        path: micl

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - name: Install Cairo svg
      run:
        sudo apt install cairosvg

    - name: Cpan
      run:  sudo cpan install -T Data::Dump  GDS2 Digest::SHA1

    - name: Silicon Chip Btree #!/usr/bin/perl -I/home/phil/perl/cpan/SvgSimple/lib/ -I/home/phil/perl/cpan/SiliconChip/lib/ -I/home/phil/perl/cpan/SiliconChipLayout/lib/ -I/home/phil/perl/cpan/SiliconChipWiring/lib/ -I/home/phil/perl/cpan/Math-Intersection-Circle-Line/lib
#-------------------------------------------------------------------------------
# Implement a B-Tree as a silicon chip.
# Philip R Brenan at appaapps dot com, Appa Apps Ltd Inc., 2023
#-------------------------------------------------------------------------------
# Database on a chip: high speed low power database look ups save data center operators money on their electricity bills.
use v5.34;
package Silicon::Chip::Btree;
our $VERSION = 20240331;                                                        # Version
use warnings FATAL => qw(all
      run:
        perl -Idtt/lib -Isvg/lib -Isc/lib -Ilayout/lib -Iwiring/lib -Imicl/lib  lib/Silicon/Chip/Btree.pm

    - name: Upload images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl -Idtt/lib -Igh/lib -M"Data::Table::Text" -e"Data::Table::Text::postProcessImagesForDocumentation(log=>1, size=>1e4)"

    - name: S3 images
      run: |
        aws configure set default.region us-east-2
        aws configure set aws_access_key_id     ${{ secrets.AWS_ACCESS_KEY_ID     }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws s3 sync lib/Silicon/Chip/ s3://vanina-andrea/SiliconChipBtree/lib/Silicon/Chip/ --exclude "*" --include "*.png" --include "*.gds"

    - uses: actions/upload-artifact@v4
      with:
        name: BTree
        path: .
