# Test 2024-04-19 at 04:00:24
# wire3c in play when going to a new level, wires drawn from longest to shortest.

name: Test

run-name: id=> 2024-04-19.07   pngs=>2  gsx=>3  gsy=>2  newChange=>1   borderDx=>16  borderDy=>44  log=>1  placeFirst=>1  spaceDx=>4  spaceDy=>4  svg=>q tree   

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SiliconChip
        path: sc

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SiliconChipLayout
        path: layout

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SiliconChipWiring
        path: wiring

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/MathIntersectionCircleLine
        path: micl

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - name: Install Cairo svg
      run:
        sudo apt install cairosvg

    - name: Cpan
      run:  sudo cpan install -T Data::Dump  GDS2 Digest::SHA1

    - name: Silicon Chip Btree id=> 2024-04-19.07   pngs=>2  gsx=>3  gsy=>2  newChange=>1   borderDx=>16  borderDy=>44  log=>1  placeFirst=>1  spaceDx=>4  spaceDy=>4  svg=>q tree   
      run:
        perl -Idtt/lib -Isvg/lib -Isc/lib -Ilayout/lib -Iwiring/lib -Imicl/lib  lib/Silicon/Chip/Btree.pm

    - name: Upload images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl -Idtt/lib -Igh/lib -M"Data::Table::Text" -e"Data::Table::Text::postProcessImagesForDocumentation(log=>1, size=>1e4)"

    - name: S3 images
      run: |
        aws configure set default.region us-east-2
        aws configure set aws_access_key_id     ${{ secrets.AWS_ACCESS_KEY_ID     }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws s3 sync lib/Silicon/Chip/ s3://vanina-andrea/SiliconChipBtree/lib/Silicon/Chip/ --exclude "*" --include "*.png"

    - uses: actions/upload-artifact@v4
      with:
        name: BTree
        path: .
